# Generated by Django 3.2 on 2021-04-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0007_auto_20210421_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
