# Generated by Django 3.2 on 2021-04-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0008_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
