# Generated by Django 3.2 on 2021-04-23 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0009_remove_profile_photo'),
        ('tasks_app', '0010_alter_profile_image'),
    ]

    operations = [
    ]
